version: "3.9"
services:
  web:
    build: .
    entrypoint: "tail -f /dev/null"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: ggbuff
      POSTGRES_PASSWORD: ggbuff
    ports:
      - "5432:5432"
