version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.6-node
    executor: ruby/default
    steps:
      - checkout
      - run: bin/bundle install
      - run: yarn install
      - run: bin/bundle exec rspec
      - run: bin/bundle exec rubocop

workflows:
  run_test:
    jobs:
      - test
