version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.6-node
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgres://ggbuff:ggbuff@localhost:5432/ggbuff_test
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      - image: cimg/postgres:14.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: ggbuff
          POSTGRES_PASSWORD: ggbuff
          POSTGRES_DB: ggbuff_test
          POSTGRES_HOST_AUTH_METHOD: trust # no password
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"

    executor: ruby/default
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - ggbuff-{{ checksum "Gemfile.lock" }}
            - ggbuff-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: |
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
            yarn install

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: ggbuff-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Setup 
          command: bin/setup

      - run:
          name: Ci
          command: bin/ci

      # Save artifacts
      - store_test_results:
          path: test_results

workflows:
  run_test:
    jobs:
      - test
