shared:
  ggxrd_dot_com:
    url: <%= ENV.fetch("GGXRD_DOT_COM_URL", nil) %>
  database_cleaner:
    clean_matches_older_than:
    old_data_threshold: <%= ENV.fetch("GGBUFF_OLD_DATA_THRESHOLD", nil) %>
  matches_loader:
    skip_older_than: <%= ENV.fetch("GGBUFF_SKIP_MATCHES_OLDER_THAN", nil) %>
